// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH170iE5cauhsu9VeU_kFFo-sMOJsE5Ns',
    appId: '1:727188531218:web:c91790b696fd80487a10cb',
    messagingSenderId: '727188531218',
    projectId: 'blood-donation-9e33c',
    authDomain: 'blood-donation-9e33c.firebaseapp.com',
    storageBucket: 'blood-donation-9e33c.appspot.com',
    measurementId: 'G-D3FNW9N09L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4XW_3xXjzdIkH2waBxPcEHQbeHYnNibs',
    appId: '1:727188531218:android:78e7fc654dde71867a10cb',
    messagingSenderId: '727188531218',
    projectId: 'blood-donation-9e33c',
    storageBucket: 'blood-donation-9e33c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9zsA6dgv2AKzp8SfZ-HsSNcTzpS5R11E',
    appId: '1:727188531218:ios:9c15d2e84904bce77a10cb',
    messagingSenderId: '727188531218',
    projectId: 'blood-donation-9e33c',
    storageBucket: 'blood-donation-9e33c.appspot.com',
    iosBundleId: 'com.example.blooddonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9zsA6dgv2AKzp8SfZ-HsSNcTzpS5R11E',
    appId: '1:727188531218:ios:332dec7be23847a57a10cb',
    messagingSenderId: '727188531218',
    projectId: 'blood-donation-9e33c',
    storageBucket: 'blood-donation-9e33c.appspot.com',
    iosBundleId: 'com.example.blooddonation.RunnerTests',
  );
}
